# YAML configuration temporarily disabled - using properties instead
# server:
#   port: 8080
# 
# spring:
#   application:
#     name: api-gateway
# 
#   cloud:
#     gateway:
#       routes:
#         - id: price-health
#           uri: http://price-service:8081
#           predicates:
#             - Path=/health/price
# 
#         - id: auth-health
#           uri: http://auth-service:8087
#           predicates:
#             - Path=/health/auth
# 
#         - id: price-service
#           uri: http://price-service:8081
#           predicates:
#             - Path=/api/price/**
#           filters:
#             - StripPrefix=1
# 
#         - id: auth-service
#           uri: http://auth-service:8087
#           predicates:
#             - Path=/api/auth/**
#           filters:
#             - StripPrefix=1
# 
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,gateway
#   endpoint:
#     health:
#       show-details: always
