redis:
  host: localhost
  port: 6379
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: price-health
          uri: http://price-service:8081
          predicates:
            - Path=/health/price
          filters:
            - RewritePath=/health/price, /health
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: '#{@ipKeyResolver}'
        - id: auth-health
          uri: http://localhost:8087
          predicates:
            - Path=/health/auth
          filters:
            - RewritePath=/health/auth, /health
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: '#{@ipKeyResolver}'
        - id: price-service
          uri: http://price-service:8081
          predicates:
            - Path=/api/price/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: '#{@ipKeyResolver}'
        - id: auth-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: '#{@ipKeyResolver}'
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG