server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: price-service
          uri: http://price-service:8086
          predicates:
            - Path=/api/price/**
          filters:
            - StripPrefix=1

        - id: price-ws
          uri: ws://price-service:8086
          predicates:
            - Path=/ws/price/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
