##realtime
GET http://localhost:8080/api/price/realtime?symbol=DOTUSDT 



### candle
GET http://localhost:8080/api/price/candles?symbol=BTCUSDT 


### api candle full
GET http://localhost:8080/api/price/candles?symbol=SOLUSDT&interval=1m&limit=100


    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "ADAUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "DOTUSDT",
    "LTCUSDT"