### =======================
### Price Service API Test
### =======================

### Get realtime price
GET http://localhost:8081/api/price/realtime?symbol=DOTUSDT

### Get candles (default 1m, limit=500)
GET http://localhost:8081/api/price/candles?limit=50&symbol=SOLUSDT

### Get candles (full params)
GET http://localhost:8081/api/price/candles?symbol=ADAUSDT&interval=1m&limit=1000&start_time=1710000000000&end_time=1710100000000

### Get supported symbols
GET http://localhost:8081/api/price/symbol

### Get history (1D interval)
GET http://localhost:8081/api/price/history?symbol=ETHUSDT&interval=1d&limit=30

### Market snapshot (multiple symbols)
GET http://localhost:8081/api/price/market_snapshot?symbols=BTCUSDT,ETHUSDT,SOLUSDT

### Top movers (gainers & losers)
GET http://localhost:8081/api/price/top_movers?limit=5


    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "ADAUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "DOTUSDT",
    "LTCUSDT"